// Code generated by MockGen. DO NOT EDIT.
// Source: modules/user/usrstorage/create.go

// Package mock_usrstorage is a generated GoMock package.
package mock_usrstorage

import (
	gomock "github.com/golang/mock/gomock"
)
