// Code generated by MockGen. DO NOT EDIT.
// Source: ./common/redis.go

// Package mock_common is a generated GoMock package.
package mock_common

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	time "time"
)

// MockRedisStorageProvider is a mock of RedisStorageProvider interface
type MockRedisStorageProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRedisStorageProviderMockRecorder
}

// MockRedisStorageProviderMockRecorder is the mock recorder for MockRedisStorageProvider
type MockRedisStorageProviderMockRecorder struct {
	mock *MockRedisStorageProvider
}

// NewMockRedisStorageProvider creates a new mock instance
func NewMockRedisStorageProvider(ctrl *gomock.Controller) *MockRedisStorageProvider {
	mock := &MockRedisStorageProvider{ctrl: ctrl}
	mock.recorder = &MockRedisStorageProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRedisStorageProvider) EXPECT() *MockRedisStorageProviderMockRecorder {
	return m.recorder
}

// GetKey mocks base method
func (m *MockRedisStorageProvider) GetKey(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKey", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKey indicates an expected call of GetKey
func (mr *MockRedisStorageProviderMockRecorder) GetKey(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKey", reflect.TypeOf((*MockRedisStorageProvider)(nil).GetKey), ctx, key)
}

// SetKey mocks base method
func (m *MockRedisStorageProvider) SetKey(key string, value interface{}, expireTime time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetKey", key, value, expireTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetKey indicates an expected call of SetKey
func (mr *MockRedisStorageProviderMockRecorder) SetKey(key, value, expireTime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKey", reflect.TypeOf((*MockRedisStorageProvider)(nil).SetKey), key, value, expireTime)
}
